### ISSUE TITLE
Config files in appimage directory

### ISSUE THREAD

**Issue by yabadaba2** [Speek-App/Speek#11]
Hello,

in the Linux version (I don't know about the other versions) it would be really helpful if Speek could use the current directory where the app is launched from to create, read and write the config files, instead of the `~/.config/speek` directory. Alternatively, it could provide a command line switch to specify the directory where configuration should be created in and read from. This would make it a portable app that could, for example, be managed completely from an external encrypted drive.

Thanks for the great work!

**Comment by Speek-App** [comment]
Thanks for opening an issue!

It now should be fixed with the most recent commit. With the next release it will be possible to specify a path when launching Speek.

For example, if you launch it with `./Speek ./new_identity` it will create a new identity in the current working directory. On the other hand, if you launch it this way `./Speek new_identity` it will create the new identity in `~/.config/speek`.
