### ISSUE TITLE
Application doesn't load on Fedora 36 

### ISSUE THREAD

**Issue by nixerdev** [Speek-App/Speek#18]
The application will not even start in Fedora 36, I tried to start it from the terminal and got the following. 

```
❯ ./Speek.Chat-1.7.0-x86_64.AppImage 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(speek:6518): GLib-GIO-ERROR **: 14:26:46.077: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)

````

**Comment by Speek-App** [comment]
Thanks a lot for opening this issue.

I played a bit around with Fedora 36 and there seems to be an issue with wayland. From what I found, GTK applications are hitting this error under wayland on GNOME 40. But it can be fixed by providing the environment variable GDK_BACKEND=x11 (important -> lowercase x).

So, as a temporary fix, you can start Speek like this:
`
GDK_BACKEND=x11 ./Speek.Chat-1.7.0-x86_64.AppImage
`

If this is indeed the issue here as well, the easiest fix for this should be to update the .desktop file provided with Speek.
