### ISSUE TITLE
?

### ISSUE THREAD

**Issue by sasholy** [Speek-App/Speek#2]
https://www.virustotal.com/gui/file/22542da60a5dec5321245d91652c3749d2a387303264cf1b06c91a7abe22eb65/relations

tnx.

**Comment by BlitGaming** [comment]
![image](https://user-images.githubusercontent.com/79034202/160229473-ba09375c-4617-43d2-885c-e4d788f1cf69.png)
Speek is detected by the antivirus due to the use of Tor.

**Comment by Speek-App** [comment]
> Speek is detected by the antivirus due to the use of Tor.

Yes, that is correct. This is because the use of Tor in Speek is detected as riskware. Also as you can see it is actually called "**Not-a-virus**:NetTool.Win32.TorTool.fyk". Generally, Kaspersky Internet Security associates “not-a-virus” with two types of applications: adware and riskware. Both types are not malicious by nature.

On another note, you can also use the version available on the [MacOS Appstore](https://apps.apple.com/us/app/speek/id1609665326) and the [Microsoft Store](https://www.microsoft.com/en-us/p/speek/9plhbg7k1wzn?activetab=pivot:overviewtab). On top of this the Macos Appstore version is also fully sandboxed for additional security.
