### ISSUE TITLE
Comparisson with Ricochet Refresh

### ISSUE THREAD

**Issue by PMunch** [Speek-App/Speek#8]
Hi, just discovered your project and started digging through the source code. This led me to discover that at least parts of it is very similar to Ricochet Refresh. The license also mentions the non-profit who backs Ricochet. What is the differences and similarities between these two projects?

**Comment by Speek-App** [comment]
Thanks for your question!

Our main goal is to create a user-friendly messenger based on Ricochet. The old Ricochet was not very appealing to most users, and we believe it is critical to onboard as many users as possible, because privacy is becoming a more important topic every day (banning of E2E encryption, client-side banning, and so on). And Ricochet Refresh has those same problems.

Therefore, we implemented many requested features, such as better file sharing and image sharing, multiple identities, backing up identities, massive UI overhaul/modernization, emoji support, easier to understand user interface (especially for people that have never used Tor), and much more that I forgot to mention. More features are currently in testing, such as group chats or planned (password protection, Tor Client Authentication, mobile versions).

I hope this answers your question. If not, please let me know.

**Comment by PMunch** [comment]
One small question, who are "we", and how do we know we can trust you? Especially for things like a mobile app most people would just have it on auto-update, without a trustworthy organization behind this it's easy to imagine someone doing a bait-and-switch and add in some malicious components.

**Comment by Speek-App** [comment]
The simplest way to find that out is to check the imprint on the website and verify that information yourself. In the end, you have to decide if you trust us.
